# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Approximate Knowledge
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://approximateknowledge.net" # the base hostname & protocol for your site, e.g. http://example.com
theme: minima
google_analytics: G-MRTTMV42N7
collections:
  - projects
header_pages:
  - words.markdown
  - other.markdown
  - about.markdown
paginate: 5
plugins:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - README.markdown
  - LICENSE
  - Gemfile
  - vendor/
